dist: Xenial
cache:
  directories:
    - node_modules
addons:
  chrome: stable
language: node_js
sudo: required
node_js:
  - "node"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" # the starting the virtual X frame buffer: Xvfb process
  - sleep 3 #wait a while before xvfb to start
script:
  - yarn test:unit
  - yarn test:e2e
after_script:
  - "sh -e /etc/init.d/xvfb stop"
